# Intermediate SQL - Sales Analysis

## Overview

This project analyzes customer behavior, customer lifetime value, customer cohorts, and customer retention using PostgreSQL.

The goal of this project is to use SQL to transform sales and customer data into meaningful business insights and answer questions related to customer value, cohort analysis, and customer churn.

## Business Questions

1. **Customer Segmentation:** Who are the most valuable customers based on lifetime value?
2. **Cohort Analysis:** How can customers be grouped based on their first purchase year?
3. **Customer Retention:** Which customers have not purchased recently and may be considered churned?

---

# 1. Customer Revenue & Cohort View

The first step was to create a SQL view called `cohort_analysis2`.

This view combines sales and customer information and creates the foundation for the remaining analysis.

### What This Query Does

* Joins the `sales` and `customer` tables.
* Calculates net revenue.
* Calculates the number of orders.
* Cleans customer names.
* Identifies each customer's first purchase date.
* Assigns each customer to a cohort year.
* Uses window functions to calculate customer-level information.

### SQL Query

```sql
CREATE VIEW cohort_analysis2 AS 
WITH customer_revenue AS ( 
    SELECT 
        s.customerkey,
        s.orderdate,
        SUM(s.quantity * s.netprice * s.exchangerate) AS net_revenue,
        COUNT(s.orderkey) AS num_orders,
        c.countryfull,
        c.age,
        c.givenname,
        c.surname
    FROM sales s
    LEFT JOIN customer c 
        ON c.customerkey = s.customerkey
    GROUP BY 
        s.customerkey,
        s.orderdate,
        c.countryfull,
        c.age,
        c.givenname,
        c.surname
)
SELECT 
    customerkey,
    orderdate,
    net_revenue,
    num_orders,
    countryfull,
    age,
    CONCAT(TRIM(givenname), ' ', TRIM(surname)) AS cleaned_name,
    MIN(cr.orderdate) OVER (
        PARTITION BY cr.customerkey
    ) AS first_purchasedate,
    EXTRACT(
        YEAR FROM MIN(cr.orderdate) OVER (
            PARTITION BY cr.customerkey
        )
    ) AS cohort_year
FROM customer_revenue cr;
```

### SQL Concepts Used

* `CREATE VIEW`
* Common Table Expressions (CTEs)
* `LEFT JOIN`
* `SUM()`
* `COUNT()`
* `GROUP BY`
* `CONCAT()`
* `TRIM()`
* `MIN()`
* Window Functions
* `PARTITION BY`
* `EXTRACT()`

---

# 2. Customer Segmentation

Customer Lifetime Value (LTV) was calculated by summing the total net revenue generated by each customer.

Customers were then divided into three segments using the 25th and 75th percentiles of lifetime value:

* **Low-Value:** Customers below the 25th percentile
* **Mid-Value:** Customers between the 25th and 75th percentiles
* **High-Value:** Customers above the 75th percentile

The analysis calculates:

* Total LTV by customer segment
* Number of customers in each segment
* Average LTV per customer

### SQL Query

```sql
WITH customer_ltv AS (
    SELECT 
        customerkey,
        cleaned_name,
        SUM(net_revenue) AS total_ltv
    FROM cohort_analysis2
    GROUP BY 
        customerkey,
        cleaned_name
),

customer_segments AS (
    SELECT 
        PERCENTILE_CONT(0.25) 
            WITHIN GROUP (ORDER BY total_ltv) 
            AS ltv_25th_percentile,
        PERCENTILE_CONT(0.75) 
            WITHIN GROUP (ORDER BY total_ltv) 
            AS ltv_75th_percentile
    FROM customer_ltv
),

segment_values AS (
    SELECT
        c.*,
        CASE 
            WHEN c.total_ltv < cs.ltv_25th_percentile 
                THEN '1-low-value'
            WHEN c.total_ltv <= cs.ltv_75th_percentile 
                THEN '2-Mid-value'
            ELSE '3-High-value'
        END AS customer_segment
    FROM customer_ltv c,
         customer_segments cs
)

SELECT 
    customer_segment,
    SUM(total_ltv) AS total_ltv,
    COUNT(customerkey) AS customer_count,
    SUM(total_ltv) / COUNT(customerkey) AS avg_ltv
FROM segment_values
GROUP BY customer_segment
ORDER BY customer_segment DESC;
```

### Analysis Performed

The query:

1. Calculates total lifetime value for every customer.
2. Calculates the 25th and 75th LTV percentiles.
3. Uses `CASE` to assign customers to value segments.
4. Calculates total LTV for each segment.
5. Counts customers in each segment.
6. Calculates average LTV per customer.

### SQL Concepts Used

* Common Table Expressions (CTEs)
* `SUM()`
* `COUNT()`
* `GROUP BY`
* `ORDER BY`
* `PERCENTILE_CONT()`
* `WITHIN GROUP`
* `CASE WHEN`
* Aggregate Functions

---

# 3. Customer Retention & Churn Analysis

The retention analysis identifies each customer's most recent purchase using the `ROW_NUMBER()` window function.

Purchases are ranked from the most recent to the oldest for each customer.

The most recent purchase is selected using `rn = 1`.

A customer is classified as **churned** when their last purchase occurred more than six months before the latest order date in the sales dataset.

### SQL Query

```sql
WITH customer_last_purchase AS (
    SELECT  
        customerkey,
        cleaned_name,
        orderdate,
        cohort_year,
        ROW_NUMBER() OVER (
            PARTITION BY customerkey 
            ORDER BY orderdate DESC
        ) AS rn,
        first_purchasedate
    FROM cohort_analysis2
),

churned_customers AS (
    SELECT 
        customerkey,
        cohort_year,
        cleaned_name,
        orderdate AS last_purchase_date,
        CASE 
            WHEN orderdate < (
                SELECT MAX(orderdate) 
                FROM sales
            ) - INTERVAL '6 months' 
            THEN 'churned'
            ELSE 'Active'
        END AS customer_status
    FROM customer_last_purchase 
    WHERE rn = 1
      AND first_purchasedate < (
          SELECT MAX(orderdate) 
          FROM sales
      ) - INTERVAL '6 months' 
)

SELECT 
    customer_status,
    cohort_year,
    COUNT(customerkey) AS num_customers,
    SUM(COUNT(customerkey)) OVER (
        PARTITION BY cohort_year
    ) AS total_customers,
    ROUND(
        COUNT(customerkey) / 
        SUM(COUNT(customerkey)) OVER (
            PARTITION BY cohort_year
        ), 
        2
    ) AS status_percentage
FROM churned_customers
GROUP BY cohort_year, customer_status;
```

### Analysis Performed

The query:

1. Identifies each customer's purchase history.
2. Uses `ROW_NUMBER()` to identify the latest purchase.
3. Finds the latest order date in the sales dataset.
4. Uses a six-month period to identify potentially churned customers.
5. Groups customers by cohort year.
6. Counts customers by active/churned status.
7. Calculates the percentage of each customer status within each cohort.

### SQL Concepts Used

* Common Table Expressions (CTEs)
* `ROW_NUMBER()`
* Window Functions
* `PARTITION BY`
* `ORDER BY`
* `CASE WHEN`
* `MAX()`
* Subqueries
* `INTERVAL`
* `COUNT()`
* `SUM() OVER()`
* `ROUND()`
* Date Calculations

---

# SQL Skills Demonstrated

This project demonstrates practical use of intermediate PostgreSQL concepts, including:

* Common Table Expressions (CTEs)
* SQL Views
* `JOIN`
* `GROUP BY`
* `ORDER BY`
* Aggregate Functions
* `CASE WHEN`
* Window Functions
* `PARTITION BY`
* `ROW_NUMBER()`
* `MIN() OVER()`
* `SUM() OVER()`
* `PERCENTILE_CONT()`
* `WITHIN GROUP`
* Date and Interval Calculations
* `EXTRACT()`
* String Cleaning
* Customer Segmentation
* Cohort Analysis
* Customer Retention Analysis
* Churn Identification

---

# Project Structure

```text
SQL-sales-analysis/
│
├── 1_customer_segmentation.sql
├── 2_create_view.sql
├── 3_retention_analysis.sql
└── README.md
```

*Rename the SQL files above if your actual filenames are different.*

---

# Tools & Technologies

* **Database:** PostgreSQL
* **SQL Environment:** DBeaver
* **Language:** SQL

---

# Key Takeaways

This project helped strengthen my understanding of using SQL for real-world business analysis.

Through this project, I practiced how to:

* Calculate customer lifetime value.
* Segment customers based on revenue.
* Calculate percentile-based customer segments.
* Create reusable SQL views.
* Identify customer first purchase dates.
* Create customer cohorts.
* Identify customers' most recent purchases.
* Analyze customer retention.
* Identify potentially churned customers.
* Calculate customer status percentages by cohort.
* Apply CTEs and window functions to solve business problems.

---

# Visualizations

Visualizations have not been created for this project yet.

Future visualizations may include:

* Customer segmentation charts
* Customer LTV distribution
* Cohort revenue analysis
* Customer retention charts
* Churn analysis by cohort
* Power BI dashboard

---

# Future Improvements

The project can be further extended by:

* Adding Power BI visualizations.
* Creating a customer retention dashboard.
* Analyzing monthly revenue trends.
* Investigating customer purchase frequency.
* Identifying high-value customers at risk of churn.
* Creating additional customer behavior segments.

---

# Author

**Nethra**

Data Analytics Portfolio Project
